### ISSUE TITLE
Notify when new WP is released

### ISSUE THREAD

**Issue by CrazyLemon** [ubuntu-si/ircbot#24]
We should use https://wordpress.org/news/category/releases/feed/ and implement channel notifications on new WP releases

**Comment by dz0ny** [comment]
https://github.com/larcher/hubot-rss-alerts/blob/master/src/rss-alerts.coffee

**Comment by zdobersek** [comment]
How often is a new release made?

Why not set up a notification alert solely for the lemony site maintainer, instead of spamming all 20 humans in the channel?

**Comment by CrazyLemon** [comment]
This issues are not new releases but security releases. Doesn't matter how often they are because security matters! 

And channel notification is needed because 'lemony site maintainer' is not the only one with Wordpress site! 
And because security releases are once a month (roughly) thats not really spamming is it?!?

**Comment by zdobersek** [comment]
I will now ignore this issue for another two months.

**Comment by CrazyLemon** [comment]
@zdobersek sooo? Its time ...

**Comment by zdobersek** [comment]
It was time, around November 29th.

I will now ignore this issue for another two months.

**Comment by mfin** [comment]
The time is NOW!

**Comment by CrazyLemon** [comment]
@zdobersek you heard the man.. the time is NOW

**Comment by zdobersek** [comment]
But what is time?
